### ISSUE TITLE
[Most recent stuff] TODO list

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#29]
Easier but I don't really feel like doing them 

- [ ] Calendar live tile
- [ ] Anime status color schemes
- [x] Better Desktop UI for calendar 🏁  v4.3.125(126).0
- [x] Better Log In page UI 🏁  v4.4.30(29).0

Biggies but I'm hyped to implement these: (in planned order)

- [x] Messages - send&receive.  🏁 v4.3.126(125).0
- [x] Favourites 🏁 v4.3.126(125).0
- [ ] Notifications :question: Is this needed? *I'm not sure*
- [x] Read-only forum... _Big and distant_ 🏁 v4.4.22(21).0
- [x] Forum with possibility to write posts. _Even Bigger and more distant_ 🏁 v4.4.22(21).0
- [x] Character&Staff Details pages 🏁  v4.4.30(29).0
- [x] New anime/manga details tab. 🏁  v4.4.30(29).0
- [ ] List compare

Misc:

- [x] How many days until anime airs info (next to grayed air day)  🏁  v4.3.124(123).0
- [x] Random PTW chooser 🏁  v4.3.124(123).0
- [x] Tags/Comments 🏁  v4.3.125(126).0
- [x] Load more top anime 🏁  v4.3.124(123).0
- [x] Fix status bar for top anime (mobile) - 🏁  v4.3.124(123).0 
- [x] Sort by Start/End dates 🏁  v4.3.125(126).0
- [x] Manga volumes 🏁  v4.3.125(126).0
- [x] Review scores 🏁  v4.3.125(126).0

___

**Bugs:**
- [x] Calendar crashes  - v4.3.18.0
- [x] Figure out what's up with those mobile crashes. 🏁  v4.3.124(3).0  Fixed a few, some are still unresolved...

___

Staging ( ⌚ ) - implemented and will be available in next update
Finished ( 🏁 )
In development ( 🚧 )

**Comment by Mordonus** [comment]
New settings as there was too much pivots to make it viable.
![image](https://cloud.githubusercontent.com/assets/6102530/15784649/c425b1f4-29b3-11e6-9616-3f555c16846a.png)

**Comment by Mordonus** [comment]
New settings will go to certification right after Microsoft approves mobile hotfix. in v4.2.6.0. ETA: Monday/Tuesday.

[WIP]
Next in queue are Articles, there will be native index:
![image](https://cloud.githubusercontent.com/assets/6102530/15804289/d2c01d3e-2b03-11e6-9d1b-f3fd3b486534.png)
And the article itself will be rendered by WebView,
It'll have custom css and only article porion will be displayed.
I'd like to open anime links in-app but we will see how this goes, it's a bit tricky and will take some time.
![image](https://cloud.githubusercontent.com/assets/6102530/15804309/13005e5e-2b04-11e6-8aa6-509f546827f3.png)

I'll be posting updates when I have something more to show. Thoughts?

**Comment by Mordonus** [comment]
Todays progess:
![image](https://cloud.githubusercontent.com/assets/6102530/15807342/d225c128-2b5b-11e6-947c-51de99265162.png)

**Comment by ZeroOmar** [comment]
looks good :+1:

**Comment by Mordonus** [comment]
Added news:
![image](https://cloud.githubusercontent.com/assets/6102530/15848758/27002fba-2c8f-11e6-9f8e-1759cd55c999.png)

Now I'll fight with light theme I guess.

**Comment by Mordonus** [comment]
Upgraded top anime section now in the works:
![image](https://cloud.githubusercontent.com/assets/6102530/15983884/2c0ce104-2fb6-11e6-8234-df4b01e96754.png)

**Comment by Mordonus** [comment]
Nice eye candy or simply too much?
![reordergif](https://cloud.githubusercontent.com/assets/6102530/15984321/cccab066-2fc6-11e6-9ad3-d6920a82e8e9.gif)

**Comment by ZeroOmar** [comment]
it's acceptable kinda looks like origin

**Comment by Mordonus** [comment]
I think I'll add this to some containers but not main one, with tons of items it looks "meh".

**Comment by Mordonus** [comment]
Collapsed hamburger will now look a little bit more sensible...
Right click = 
![image](https://cloud.githubusercontent.com/assets/6102530/15984960/16be8a10-2fdd-11e6-9723-bb1f2b078e7e.png)

Same goes for manga and top categories.

**Comment by ZeroOmar** [comment]
nice :+1:

**Comment by Mordonus** [comment]
This is going to be tricky on mobile... I'm thinking about adding button to TopAnime button which will display such flyout.

**Comment by ZeroOmar** [comment]
mobile already have something similar.
pressing on the "username - watching" brings similar flyout

**Comment by Mordonus** [comment]
Yeah but it's not a problem, this is the problem:
![image](https://cloud.githubusercontent.com/assets/6102530/15985066/f51f7414-2fe1-11e6-823c-f16fe234cbaa.png)

**Comment by ZeroOmar** [comment]
yeah the mobile hamburger menu is different it doesn't have that expandable menu

maybe make it like the anime list
where all this options appear as a flyout from the title bar

**Comment by ZeroOmar** [comment]
there is a typo in favorites :arrow_up:

**Comment by Mordonus** [comment]
It's not a typo :D

enGB -> favourites , colour
enUS -> favorites, color

**Comment by ZeroOmar** [comment]
oh, sorry

**Comment by Mordonus** [comment]
+1 ^^

Mobile build should be up sometime soon. Deployment is bugged in current insider (redstone) build and it's painful to dubug anything...

**Comment by ZeroOmar** [comment]
my phone had alot of performance issues with windows 10 so I switched back to windows 8.1
so I can't test the mobile version of your app :frowning:

**Comment by Mordonus** [comment]
Sure, versions on release preview ring shouldn't be that bad. Do you happen to have unsupported device or just fast ring?

**Comment by ZeroOmar** [comment]
yes, I have an unsupported device (lumia 630)
which was removed from the supported insider devices

**Comment by Mordonus** [comment]
Oh, I did have 630 with W10 and I know the pain. 512M of RAM is simply not enough... 640 is great device though :D

**Comment by Mordonus** [comment]
13.06.2016 - Cleanup + TODO Updates

**Comment by Mordonus** [comment]
Successfully sent mal message, don't ask me when this will go live. ^^

**Comment by ZeroOmar** [comment]
I forgot to tell you about this before 
- [ ] support for "re-watching" status in anime

**Comment by Mordonus** [comment]
It's gonna be tricky and there are more important things I guess.

**I've figured out how to favourite characters!** Next update will be definitely focused on bringing more functionality:

- Forums
- Messages/Notifications
- Favourites

This is going to take some time as I have exams coming up and it's quite complicated to get everything to work.

**Comment by Mordonus** [comment]
A bit of progress:
![image](https://cloud.githubusercontent.com/assets/6102530/16170208/4d5d53b2-354b-11e6-9b7b-03f727618130.png)

I'm going to keep it simple as it is on MAL page. Building whole elaborate messaging system isn't really something I want to do right now.

**Comment by Mordonus** [comment]
A pinch of progress:
![image](https://cloud.githubusercontent.com/assets/6102530/16176939/fda230bc-361d-11e6-8c2e-d991619e83be.png)

**Comment by Mordonus** [comment]
Just thought this about this small addition while browsing seasonal :)
![image](https://cloud.githubusercontent.com/assets/6102530/16220859/bc71915a-378f-11e6-90b3-ac2d02b39219.png)

**Comment by Mordonus** [comment]
Crazy times in university, update drought will continue for at least a week :(

**Comment by Mordonus** [comment]
Added some more TODO stuff + ordered what I want to put in upcoming updates.

University progress 2/6 if anyone bothers :D

**Comment by Mordonus** [comment]
Added random selector. I may be able to push update tommorow ^^.

**Comment by Mordonus** [comment]
Added option to load up to 200 top anime items.

**Comment by Mordonus** [comment]
v4.3.124(3).0 is now in certification!

**Comment by Mordonus** [comment]
Added manga volumes, sorting by start/end dates. Now working on tags.

**Comment by Mordonus** [comment]
Added tags with improved search!

![image](https://cloud.githubusercontent.com/assets/6102530/16586871/4aeabe00-42c8-11e6-85c5-1df99153df65.png)
![image](https://cloud.githubusercontent.com/assets/6102530/16586882/5ba0b150-42c8-11e6-8dda-195534b82931.png)

**Comment by Mordonus** [comment]
Added detailed scores to reviews.

I'm wrapping up v4.3.126(5).0 here. I'll push it to certification in a few hours.

**Comment by Mordonus** [comment]
I decided to upgrade desktop calendar UI -> I'll push update tomorrow morning ^^

**Comment by Mordonus** [comment]
v4.3.126(5).0 now in certification!

Changelog:
```
09.07.2016 - v4.3.125.0 & v4.3.126.0
Added manga volumes support.
Added option to focus on either chapters or volumes.
Added tags.
Improved search and added suggestion based on tags.
Added detailed score listing to reviews.
Tweaked search page a little bit.
Bugfixes, optimizations, cleanup yaddi yadda... ^^

Desktop specific:
Calendar summary page UI has been tweaked.
Added option to display scrollbar in articles and news.
```

**Comment by Mordonus** [comment]
Favourites are coming!
![image](https://cloud.githubusercontent.com/assets/6102530/16688972/ec41b0e2-4520-11e6-96c7-ebacdd6c6c4f.png)
I won't do anything robust with them as obtaining and updating this information is quite cumbersome.

I'll be adding character & staff listing to details in order to add theese favourites too. :)

**Comment by Amrykid** [comment]
Are there any plans to sync to the Windows Calendar on both platforms?

**Comment by Mordonus** [comment]
I don't use windows calendar but I'll see what I can do.

**Comment by Mordonus** [comment]
Favourite characters:

![image](https://cloud.githubusercontent.com/assets/6102530/16715345/56300ffe-46dd-11e6-96bd-241c41902d93.png)

With that I'm done with favs and I'm going to polish messaging now. I'm not sure about notifications though as it's going to be rough with these means of obtaining data.

**Comment by Mordonus** [comment]
I'm going to make mobile version work with continuum, it won't be full dekstop implementation but it'll be usable...

**Comment by Amrykid** [comment]
Yeah, that functionality would come automatically if you were using screen-based layout. ;)

**Comment by Mordonus** [comment]
Shhhh...

**Comment by Mordonus** [comment]
Favs and messaging are going to be unstable... they have already changed structure 3 times and I even haven't released this thing yet...

**Comment by Mordonus** [comment]
Anyone knows how this looks in continuum?
![image](https://cloud.githubusercontent.com/assets/6102530/16850398/2ff035ec-49ff-11e6-9abc-3486feb58b24.png)

Is there even this bar?

**Comment by Amrykid** [comment]
IIRC, that titlebar does exist in continuum.

**Comment by Mordonus** [comment]
Okay, about this calendar...  Is creating simple recurring entries enough for you?

**Comment by Mordonus** [comment]
@Amrykid You won, I'm working on combining as much as I can into one solution.

**Comment by Amrykid** [comment]
It'll definitely make it easier in the long run for you.

I've already went through the pain of trying to maintain two different versions (desktop and mobile) of an app. I wouldn't want someone to go through that same pain again, heh.

**Comment by Mordonus** [comment]
Yup, never ever again. Tbh it turned out to be easier than I thought ^^ Now I have to test everything and adjust some minor things...

 (praise ReSharper)

**Comment by Mordonus** [comment]
Anyone up for testing "unified" (somewhat) version? There are huge changes in the code and I don't really want to tremble in fear after submitting update to the store...

**Comment by ZeroOmar** [comment]
I'll test on desktop since my phone is not win 10 anymore

**Comment by Mordonus** [comment]
Okay, updated *whole* project structure, updated sdks, unified majority of the code, added hacky favourites and MAL messaging... I mean... ummm... something *has* to be bugged.

x64
https://1drv.ms/u/s!Am1xQK-HVf_IkbU-RQlRnhescwAqaQ

ARM
https://1drv.ms/u/s!Am1xQK-HVf_IkbU_AXoQZjh_KwZABw

**Comment by thepaulomalley** [comment]
Current Desktop Build crashes whenever it tries to load Top Manga

Can confirm that the title bar doesn't show on continuum.
Calendar integration would be amazing to have!

**Comment by Mordonus** [comment]
Calendar is already here, there are buttons on calendar page.

I cannot reproduce crashes on top manga but I suspect hummingbird manga response.

**Comment by Mordonus** [comment]
Next preview version with more fixes and adjustments + issue #42. Only desktop this time:

**x64**
https://1drv.ms/u/s!Am1xQK-HVf_Ikbww8oTq1NJ-V50VKg

**Comment by Mordonus** [comment]
Okay, now comes the worst part where I have to write changelog and make some screenshots... I hope to push update to certification today...

**Comment by Mordonus** [comment]
Code has been moved...
![image](https://cloud.githubusercontent.com/assets/6102530/17018673/21468f70-4f39-11e6-82bb-576ed1249bfe.png)

**Comment by Mordonus** [comment]
v4.4.6(5).0 is in certification!

```
25.07.2016 -  v4.4.6.0 & v4.4.5.0

Added favourites.
Added messaging.
Cleaned up project structure and unified codebases.
You can now export show to Windows calendar from calendar page.
Added characters & voice actors and staff listings to anime details.
Mobile version should be now usable with Continuum.
Fixed TONS of bugs (more on github).
Bazillion UI adjustments and minor changes.

```

**Comment by Mordonus** [comment]
Fight with forums has started! Bring it on!

This is how I see main board page:
![image](https://cloud.githubusercontent.com/assets/6102530/17067230/22badfb0-504b-11e6-9e41-aedc2eb4753e.png)

**Comment by Mordonus** [comment]
Okay is there someone with knowledge of mysterious yet powerful magic known as css and willing to tweak MAL's topic page?

**Comment by Mordonus** [comment]
It was rough but I did mange to do something!

![image](https://cloud.githubusercontent.com/assets/6102530/17084448/4eb08880-51be-11e6-91ff-c3888b674409.png)

**Comment by Mordonus** [comment]
And board page:

![image](https://cloud.githubusercontent.com/assets/6102530/17084697/eae2363a-51c4-11e6-9635-0501f0fd00c4.png)

This is how I see the layout of forum, now I have to hook everything up and make it usable...

**Comment by Mordonus** [comment]
I got myself an internship so development will slow down a bit but I'll try to do something everyday :) Forums are now mostly **usable** I'll be focusing on QoL now, any wishlist?

**Comment by Kimod** [comment]
So after you are done with forums and making them more user friendly, could you look into some more issues from issue #42? ^^

**Comment by Mordonus** [comment]
That's the plan. There may be update next week with "stuff" but it depends on how much time will I have over the weekend.

**Comment by Mordonus** [comment]
Build with bugfixes from @Kimod's super awesome list #42  (2nd one).

x64:
https://1drv.ms/u/s!Am1xQK-HVf_IkdJe2T917pFMChEhnQ

ARM:
https://1drv.ms/u/s!Am1xQK-HVf_IkdJf3uMnxmR-5yTxBg

**Comment by Mordonus** [comment]
Profile comments!

![image](https://cloud.githubusercontent.com/assets/6102530/17275074/113e98d8-56fb-11e6-94e3-8c138ba8f084.png)

**Comment by Mordonus** [comment]
Next build with profile comments , profile history and tons of stuff from #42 

x64
https://1drv.ms/u/s!Am1xQK-HVf_IkdMGLdSF12rZOZAODw

**Comment by Mordonus** [comment]
x64 4.4.11.0
https://1drv.ms/u/s!Am1xQK-HVf_IkdZiIIjbT12-cSQ3gw

**Comment by Kimod** [comment]
ok, it doesn't crash now, which is always good, right?
* Sometimes history doesn't load and also you have a little tipo - "epmty" - http://puu.sh/qkMu8.gif
* The back arrow stays there when I go from history to my "Anime List". And when I view my history through my profile, the back arrow is there, but when i view my history through that icon in hamburger menu, the back arrow isn't there - http://puu.sh/qkMCi.gif

Sorry for the delay, I was eating lunch ^^

**Comment by Mordonus** [comment]
First mobile build with new stuff:
(I'd like to treat these like RC's without changelog but we all know how this will turn out...)

ARM v4.4.14.0
https://1drv.ms/u/s!Am1xQK-HVf_IkdZjnvZfo5-3ZfuZ2w

x64 v4.4.13.0
https://1drv.ms/u/s!Am1xQK-HVf_IkdZkScENmvUmNZHslQ

**Comment by Mordonus** [comment]
Update just went to certification:

```
03.08.2016 -  v4.4.16.0 & v4.4.15.0

Added profile comments.
Added profile history.
Improved organisation of profile page.
Gave some love to light theme.
Search will be now more accurate and there will be delay after typing in query.
Resolved issues with being unable to load more items on mobile.
Selecting at random will be now smarter.
Fixed visual bug with start/end dates.
Fixed bug where refresh button could create duplicates.
Status bar will now correctly show show titles and other headers.
You can now select and copy text from header in anime details.
Navigation mechanisms have been rewritten.
Profile page will no longer show empty favourites.
Resolved with adaptation issues in recommendations page.

```

**Comment by Mordonus** [comment]
Update is up... Posted news on appraisin, go raise it ^^

**Comment by ZeroOmar** [comment]
the new windows store says that your app is avalable for Xbox, hololens and surface hub

![untitled](https://cloud.githubusercontent.com/assets/18592104/17363939/a4701abc-597d-11e6-9b14-d3792300a43e.png)

**Comment by Mordonus** [comment]
That's good? xd

In dev center they are disabled so visual bug I guess, or UWP just works everywhere.

**Comment by ZeroOmar** [comment]
I wonder how it looks like on hololens

**Comment by CookieyedCodes** [comment]
Great app man, theirs 3 bugs i found and a tip im gonna give to hopefully give you more downloads:)
Bug: in general settings the last watched button isnt saveing (it weird as setting nothing and desending dose the same thing),
The app is not decting my Hummingbird manga at all,
and when you click the sidebar with (general, details,ect) no infomation apears below when I click it,

but other then them you have a great app man keep up the good work. :)

Tips: maby make the increment and decrcrment buttons that hide under the anime icon a bit more obviouse that their under as I only found that out today by mistake
and try to get on the hummingbird app page it might give some more downlodes

**Comment by Mordonus** [comment]
Hello, unfortunately hummingbird doesn't provide "official" manga API so I did a bit of hacking back then but because of very low hummingbird traffic I'm focusing on mal.

I don't really feel like it would be fair to ask them to put this app on their page, the name is a bit off + majority of info is pulled from mal + more mal specific features.

As for dragging/swiping on items you are probably right (you are not the first)

**Comment by CookieyedCodes** [comment]
All of that is fair enough man, keep at the great work:)

**Comment by Mordonus** [comment]
Hmm we have a bit old info here... v4.4.22(21) just went to certification!

```
13.08.2016 -  v4.4.22.0 & v4.4.21.0

Added forums!
Fixed mobile sort by start/end date.
Resolved multiple navigation issues in mobile version.
Visually tweaked search page.
Clicking on any anime item should always trigger details navigation.
Desktop upper navigation bar will behave better now.
Small tweaks and fixes everywhere :)

```

**Comment by Mordonus** [comment]
Character details!

![image](https://cloud.githubusercontent.com/assets/6102530/17648499/13787826-6218-11e6-88d0-95c467d6b30d.png)

Now I'm going to add staff details :)

**Comment by Mordonus** [comment]
Staff details!

![image](https://cloud.githubusercontent.com/assets/6102530/17651240/1d398102-6263-11e6-9e6b-48d3845262b9.png)

Now I'm going to #42 and after that back to forums... and I'll call this an update. Any ideas for future bigger stuff?

**Comment by Kimod** [comment]
Since you are asking, might as well suggest some stuff ^^ Rewatching support, Affinity with user, about me in profile and maybe comparing lists? ^^

**Comment by Mordonus** [comment]
Hah, I even forgot about list comparison but details will be first I guess (more html scrapping... yay... said no one ever).

I should be able to add more seasons selector in next update, we'll see about "about me" because I'll probably have to render this as html and takes it's time.

**Comment by Mordonus** [comment]
Here you go :)

![image](https://cloud.githubusercontent.com/assets/6102530/17657307/6ca9ad2a-62c2-11e6-82b4-1db4ab48639b.png)

**Comment by Mordonus** [comment]
Bam!

![image](https://cloud.githubusercontent.com/assets/6102530/17658565/de334366-62cc-11e6-9d9a-400748d971b4.png)

Not the best possible execution because of WebView but it has to suffice.

**Comment by Mordonus** [comment]
New build! Desktop only this time.

What's inside?
Staff&Character details, About me on profile page, custom season selection, #42fixes, details from MAL page (for manga too!) and improved log-in page.

I've tested this but not very thoroughly... have fun :D

x64:
https://1drv.ms/u/s!Am1xQK-HVf_Ikogd9tip6N5cyyuZWw

**Comment by Drutol** [comment]
Next build! Mainly fixes from #49 + character search + #47 + fixes from nowhere ^^

Now I'm going to look at mobile :)

x64:
https://1drv.ms/u/s!Am1xQK-HVf_Ikogew89CGkWWh8UJ5Q

**Comment by Drutol** [comment]
Next build*s*!

Fixes + first mobile build with new stuff + #49 

ARM:
https://1drv.ms/u/s!Am1xQK-HVf_IkosHKj4JmM_O9QBLLA
x64:
https://1drv.ms/u/s!Am1xQK-HVf_IkosGUxDL2KHNIb_Uxg

**Comment by Drutol** [comment]
I'll submit this to certification later today.

```
23.08.2016 v4.4.30.0 & v4.4.29.0

Added character details page.
Added staff details page.
Added character serach page.
Added "about me" section in profile page.
Added custom anime season selection window.
Added new details tab in anime and manga details pages.
Added option to pull higher resolution images with setting.
Revamped log-in page to look a bit more appealing.
Resolved issues with vanishing airing day labels.
Fixed issues with start/end dates and status change prompts.
Small visual upgrade for compact list.
Resolved theme discrepancies with favourite buttons.
Fixed missing favourites on certain profile pages.
Crashfix for detailed grid view.
Mobile now uses mobile forums site. (wip)
Tons of fixes and miscellaneous changes.
```

**Comment by Drutol** [comment]
Time for new TODO issue!
