### ISSUE TITLE
Brand old TODO list!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#52]
Go here for more specific details
https://github.com/Drutol/MALClient/projects/4
- [x] Multiplatfrom solution with UWP restored to its former glory. 🏁 
- [x] Rewatching support 🏁  v5.0.18(19).0
- [x] Finish forums 🏁  v5.0.18(19).0
- [ ] List comparing
- [x] Notifications 🏁  v5.0.18(19).0
- [ ] Clubs
- [x] **Begin** Android development :checkered_flag: 
- [x] New logo + optional name change :checkered_flag: v5.0.10(11).0
- [x] Watched topics 🏁 v5.0.25(24).0
- [ ] Social share
- [x] Promotional Videos 🏁 v5.0.29(28).0
- [x] Handy search (in off section) 🏁 v5.0.29(28).0
- [x] Wallpapers 🏁 v5.1.4(5).0
- [x] Promotional videos - most popular page 🏁 v5.1.4(5).0
- [ ] Notification page
- [ ] Recent Friend Updates
- [x] Manga recoms 🏁 v5.1.7(6).0
- [x] Articles&News live tiles 🏁 v5.1.7(6).0

(no order)

---

Staging ( ⌚ ) - implemented and will be available in next update
Finished ( 🏁 )
In development ( 🚧 )

**Comment by Amrykid** [comment]
Bringing Xamarin in to the mix is going to be pretty cool.

When you say bring UWP to its former glory, does that mean you'll be having the PC and Mobile solution be the same project (instead of separate ones in the same solution) this time around?

Off-topic: It caught me off-guard when I noticed that you changed your GitHub name.

**Comment by Drutol** [comment]
I'm hyped for Xamarin! I'm currently fighting with android and custom roms though, as I have very old device(android 2.3 :D) but it's better than nothing.

By restoring to the former glory I mean hooking everything up to new adapters and creating new converters. I had everything visibility related not in boolean but in Visibility enum for example.

Yup, I'm dropping this old nickname and I just had to do it at some point ^^

**Comment by Drutol** [comment]
https://github.com/Drutol/MALClient/projects/4

Most up to date list
